### ISSUE TITLE
Python version should be bumped to 3.4 or 3.5

### ISSUE THREAD

**Issue by thiblahute** [alexlarsson/gnome-sdk-images#10]
3.3 is getting old :)

**Comment by alexlarsson** [comment]
Python is inherited from the yocto base, and 1.8 has python 3.3. When we rev to a newer version we'll get a newer python. However, that is not something we do in a stable release series.

**Comment by thiblahute** [comment]
Got it, I had to patch meson to be able to use it with py 3.3, but it is fine. Also we probably want to install meson and ninja  in the base Sdk.
