### ISSUE TITLE
Missing PyGObject for python2

### ISSUE THREAD

**Issue by thiblahute** [alexlarsson/gnome-sdk-images#16]
PyGobject seems to be avalaible only for python3, not python2.

**Comment by alexlarsson** [comment]
Yeah. I try to keep old things out of the runtime since it will need to be kept compat for a long time. Ideally it shouldn't even have python2, but gotta be pragmatic here...

**Comment by alexlarsson** [comment]
Bundling pygtk2 should not be too hard though.

**Comment by thiblahute** [comment]
Not saying pygtk2 here but PyGobject (GI) with python2 support, which sounds legit since you still have python2... well as you want :)
