### ISSUE TITLE
pkg-config --variable=girdir gobject-introspection-1.0 does not refer to /self

### ISSUE THREAD

**Issue by dsvensson** [alexlarsson/gnome-sdk-images#3]
Not sure if this is the place, or if it's some issue with gobject-introspection-1.0 upstream, the end result is the same at least.

When building libgee within xdg-app:

```
/usr/bin/install -c -m 644 Gee-0.8.gir '/usr/share/gir-1.0'
/usr/bin/install: cannot create regular file ‘/usr/share/gir-1.0/Gee-0.8.gir’: Read-only file system
```

And as subject suggests:

```
$ xdg-app build . pkg-config --variable=girdir gobject-introspection-1.0 
/usr/share/gir-1.0
```

...and same applies to girepository-1.0 variable.

**Comment by alexlarsson** [comment]
Yeah, this is:
https://bugzilla.gnome.org/show_bug.cgi?id=639782

**Comment by dsvensson** [comment]
Ah excellent, tracking that instead.
