### ISSUE TITLE
PYTHONPATH and GST_PLUGIN_PATH should point to the /app/ prefix

### ISSUE THREAD

**Issue by thiblahute** [alexlarsson/gnome-sdk-images#8]
In order to make it simpler for application developpers to use the bundle, we should make sure that important env variables are properly set by default, at least those two should be set:

```
GST_PLUGIN_PATH=/app/lib/gstreamer-1.0
PYTHONPATH=/app/lib/python3.3/site-packages
```

**Comment by alexlarsson** [comment]
Pythonpath should not be needed, as we ship some magic config thing:
$ python3 -c "import sys; print(sys.path)" 
<alex_> ['', '/usr/lib/python33.zip', '/app/lib/python3.3/site-packages', '/usr/lib/python3.3', '/usr/lib/python3.3/plat-linux', '/usr/lib/python3.3/lib-dynload', '/usr/lib/python3.3/site-packages']

**Comment by alexlarsson** [comment]
In fact, PYTHONPATH is problematic as it is read by both python2 and python3

**Comment by alexlarsson** [comment]
Latest version sets GST_PLUGIN_PATH
